### ISSUE TITLE
The CI for the library should offer a repository dispatch

### ISSUE THREAD

**Issue by jason-fox** [telefonicaid/iotagent-node-lib#1021]
Related to https://github.com/telefonicaid/lightweightm2m-iotagent/pull/248#issuecomment-818647123

At the moment whenever changes are made in the IoT Agent Node library in this repo here, they are not witnessed downstream until a new build is triggered. The CI for this  repo should offer a trigger to the IoT Agents whenever code is successfully merged into master. An exisiting [GitHub Action](https://github.com/peter-evans/repository-dispatch) can already do this provided that a [PAT token](https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token) is added a a secret within this repository. You'll need something like:

```yaml
jobs:
  build:
    # Main workflow job that builds, tests, etc.

  dispatch:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    strategy:
      matrix:
        repo: ['telefonicaid/iotagent-json, 'telefonicaid/iotagent-ul, 'telefonicaid/iotagent-lightweightm2m-iotagent']
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: iot-agent-node-lib
```

Each of the IoT Agents CI could then be altered to handle both a manual trigger and the `iot-agent-node-lib` event e.g.:

```yaml
name: CI
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  repository_dispatch:
    types:
      - iot-agent-node-lib
  workflow_dispatch:
```

This would avoid nasty discoveries if any downstream project is relying on something it shouldn't.

**Comment by fgalan** [comment]
PRs related with this issue:

- https://github.com/telefonicaid/iotagent-node-lib/pull/1103
- https://github.com/telefonicaid/iotagent-ul/pull/514
- https://github.com/telefonicaid/iotagent-json/pull/593
- https://github.com/telefonicaid/lightweightm2m-iotagent/pull/254
- https://github.com/telefonicaid/sigfox-iotagent/pull/112

GitHub has auto-close this issue, but maybe is wiser to let it opened while we can check that the system is working

**Comment by jason-fox** [comment]
Even better would be to close it after we've got dispatch working with `FIWARE/iotagent-isoxml` - I guess you'll need a FIWARE PAT (with minimal rights) from me right? Assuming TEF can dispatch to FF, this should also be extended to informing ATOS (for the LoRaWAN IoT Agent)

**Comment by fgalan** [comment]
No problem in adding additional token as tokens in this repo... however, how this could be managed in ci.yml? What we have now is:

```
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: iot-agent-node-lib
```

But I understand more of these secrets.xxxx should be added there (i.e. REPO_ACCESS_TOKEN_FF, REPO_ACCESS_TOKEN_ATOS, etc.).
