### ISSUE TITLE
Group Provision param: entityNameExp doen't seem to work.

### ISSUE THREAD

**Issue by mrutid** [telefonicaid/iotagent-node-lib#1285]
Given the following group:

```
{
    "attributes" : [ 
        {
            "name" : "myAtt",
            "type" : "text"
        }
    ],
    "resource" : "/iot/json",
    "apikey" : "key",
    "type" : "MySensorGroup",
    **"entityNameExp" : "'expression'+id",**
    "service" : "myserv",
    "subservice" : "MySServ",
    "expressionLanguage" : "jexl",
}
```

We get the following NGSI update:

http://eob67h2l2jqr93n.m.pipedream.net/v2/entities/MySensorGroup2:007/attrs?type=MySensorGroup2

instead of 

http://eob67h2l2jqr93n.m.pipedream.net/v2/entities/expression007/attrs?type=MySensorGroup2

**Comment by MayankSingh-NEC** [comment]
Hi @mrutid  and @fgalan , I'm working on this issue. Could you please provide more info regarding the issue? and on how to reproduce this issue?

**Comment by AlvaroVega** [comment]
I'm not able of reproduce it, I'm obtaining an NGSIv2 update to `v2/entities/expression007/attrs?type=MySensorGroup2''

**Comment by MayankSingh-NEC** [comment]
Hi @mrutid  and @AlvaroVega 
![entityNameExp](https://user-images.githubusercontent.com/103482738/199656155-c020829d-f691-411c-abe0-854d764d700b.PNG)
, I'm also investigating this issue.
But I'm getting the NSGI update as ""url": "http://localhost:1026/v2/entities/LivingRoomSensor/attrs?type=Device","
The steps, I'm following are:

1. Provisioning A Service Group

curl -iX POST \
  'http://localhost:4041/iot/services' \
  -H 'Content-Type: application/json' \
  -H 'fiware-service: smartgondor' \
  -H 'fiware-servicepath: /gardens' \
  -d '{
 "services": [
   {
     "apikey":      "1234",
     "cbroker":     "http://orion:1026",
     "entity_type": "Device",
     "resource":    "/iot/d",
	 "entityNameExp": "'LivingRoomSensor' + motion001"
   }
 ]
}'

2. Provisioning An Individual Device

curl -iX POST -H "Fiware-Service: samrtgondor" -H "Fiware-ServicePath: /gardens" -H "Content-Type: application/json" -H "Cache-Control: no-cache" -d '{
    "devices": [
        {
            "device_id": "motion001",
            "entity_name": "LivingRoomSensor",
            "entity_type": "Device",
            "attributes": [
                  { "object_id": "t", "name": "Temperature", "type": "celsius" },
                  { "object_id": "l", "name": "Luminosity", "type": "lumens" }
            ]
        }
    ]
}

' 'http://localhost:4041/iot/devices'

3. Sending Measures With The Device

mosquitto_pub -t /1234/motion001/attrs -m '{"l":4,"t": "31.5"}'


Could you please let me know the steps to reproduce the expected NGSI-v2 link? PFA.

**Comment by fgalan** [comment]
Maybe related: PR https://github.com/telefonicaid/iotagent-node-lib/pull/1284

**Comment by mapedraza** [comment]
Test performed:

## Deployment
```yaml
 iot-agent:
    image: telefonicaiot/iotagent-json:latest
    hostname: iot-agent
    container_name: iot-agent
    depends_on:
      - mongo-db1
    expose:
      - "${IOTA_NORTH_PORT}"
      - "${IOTA_SOUTH_PORT}"
    ports:
      - "${IOTA_NORTH_PORT}:${IOTA_NORTH_PORT}" 
      - "${IOTA_SOUTH_PORT}:${IOTA_SOUTH_PORT}"
    environment:
      - IOTA_LOG_LEVEL=DEBUG
      - IOTA_MONGO_HOST=mongo-db1
      - IOTA_MONGO_PORT=${MONGO_DB_PORT} 
      - IOTA_MONGO_DB=iotagentjson 
      - IOTA_DEFAULT_RESOURCE=/iot/json
      - IOTA_CB_NGSI_VERSION=v2 
      - IOTA_APPEND_MODE=false
```

## Service creation

```bash
curl -iX POST 'http://localhost:4041/iot/services' \
-H 'fiware-service: service' \
-H 'fiware-servicepath: /' \
-H 'Content-Type: application/json' \
--data-raw '{
    "services": [
        {
            "apikey": "service1",
            "cbHost": "http://orion:1026",
            "entity_type": "Device-1",
            "resource": "/iot/json",
            "expressionLanguage" : "jexl",
            "entityNameExp": "'EntityNameByExp'",
            "attributes": [
                {
                    "object_id": "t",
                    "name": "status",
                    "type": "Property"
                }
            ]
        }
    ]
}'
```

## Result - Orion

```json
[
    {
        "TimeInstant": {
            "metadata": {},
            "type": "DateTime",
            "value": "2022-11-30T15:20:15.145Z"
        },
        "id": "Device-1:dev1",
        "status": {
            "metadata": {
                "TimeInstant": {
                    "type": "DateTime",
                    "value": "2022-11-30T15:20:15.145Z"
                }
            },
            "type": "Property",
            "value": 5
        },
        "type": "Device-1"
    }
]
```

## Conclusion

It seems entityNameExp is not working. It is `"entityNameExp": "'EntityNameByExp'",` well defined?
