### ISSUE TITLE
appendMode/IOTA_APPEND_MODE is not overwritten by autoprovision

### ISSUE THREAD

**Issue by djs0109** [telefonicaid/iotagent-node-lib#1301]
from #1016

I found that the environment variable `appendMode/IOTA_APPEND_MODE` is not truly overwritten by `autoprovision` flag in group or device provision. However, it should be overwritten, as stated in [documentation](https://github.com/telefonicaid/iotagent-node-lib/blob/master/doc/installationguide.md).

What I try:
1. create a simple service group, while let the `appendMode/IOTA_APPEND_MODE=False` by default
POST /iot/services
```
{
 "services": [
   {
    "resource": "/iot/json",
    "apikey": "autoprovision",
    "expressionLanguage": "legacy",
    "explicitAttrs": false,
    "autoprovision": true
   }
 ]
}
```

2. I send an anonymous measurement. Then an entity is created **without any attributes**.
When I check the logs in Context Broker I found that the `actionType` is `update`
`INFO@2022-11-16T11:14:08.918Z  logTracing.cpp[148]: Request received: POST /v2/op/update, request payload (269 bytes): {"actionType":"update","entities":[{"humidity":{"type":"string","value":111, ... response code: 422`

3. I restart the IoTagent while setting the `IOTA_APPEND_MODE=true`.  I send the same measurement again. A new attribute is create d in the Context Broker. And I found that the `actionType` turn to `append` now
`INFO@2022-11-16T11:14:34.952Z  logTracing.cpp[148]: Request received: POST /v2/op/update, request payload (269 bytes): {"actionType":"append","entities":[{"humidity":{"type":"string","value":111, ... response code: 204`

**Comment by mapedraza** [comment]
I just performed this test:

## Deployment

```yaml
  iot-agent:
    image: telefonicaiot/iotagent-json:latest
    hostname: iot-agent
    container_name: iot-agent
    depends_on:
      - mongo-db1
    expose:
      - "${IOTA_NORTH_PORT}"
      - "${IOTA_SOUTH_PORT}"
    ports:
      - "${IOTA_NORTH_PORT}:${IOTA_NORTH_PORT}" 
      - "${IOTA_SOUTH_PORT}:${IOTA_SOUTH_PORT}" 
    environment:
      - IOTA_LOG_LEVEL=DEBUG 
      - IOTA_MONGO_HOST=mongo-db1 
      - IOTA_MONGO_PORT=${MONGO_DB_PORT}
      - IOTA_MONGO_DB=iotagentjson 
      - IOTA_DEFAULT_RESOURCE=/iot/json
      - IOTA_CB_NGSI_VERSION=v2 
```

## Service creation

```json
curl -iX POST 'http://localhost:4041/iot/services' \
-H 'fiware-service: service' \
-H 'fiware-servicepath: /' \
-H 'Content-Type: application/json' \
--data-raw '{
    "services": [
        {
            "apikey": "service1",
            "cbHost": "http://orion:1026",
            "entity_type": "Device-1",
            "resource": "/iot/json",
            "explicitAttrs": false,
            "autoprovision": false,
            "attributes": [
                {
                    "object_id": "s",
                    "name": "status",
                    "type": "Property"
                }
            ]
        },
        {
            "apikey": "service2",
            "cbHost": "http://orion:1026",
            "entity_type": "Device-2",
            "resource": "/iot/json",
            "explicitAttrs": false,
            "autoprovision": true,
            "attributes": [
                {
                    "object_id": "s",
                    "name": "status",
                    "type": "Property"
                }
            ]
        },
        {
            "apikey": "service3",
            "cbHost": "http://orion:1026",
            "entity_type": "Device-3",
            "resource": "/iot/json",
            "explicitAttrs": true,
            "autoprovision": false,
            "attributes": [
                {
                    "object_id": "s",
                    "name": "status",
                    "type": "Property"
                }
            ]
        },
        {
            "apikey": "service4",
            "cbHost": "http://orion:1026",
            "entity_type": "Device-4",
            "resource": "/iot/json",
            "explicitAttrs": true,
            "autoprovision": true,
            "attributes": [
                {
                    "object_id": "s",
                    "name": "status",
                    "type": "Property"
                }
            ]
        }
    ]
}'
```

## Data sent

```bash
curl -L -X POST 'http://localhost:7896/iot/json?k=service1&i=dev1' \
-H 'Content-Type: application/json' \
--data-raw '{ "t": 5}' && \ 
curl -L -X POST 'http://localhost:7896/iot/json?k=service2&i=dev2' \
-H 'Content-Type: application/json' \
--data-raw '{ "t": 5}' && \ 
curl -L -X POST 'http://localhost:7896/iot/json?k=service3&i=dev3' \
-H 'Content-Type: application/json' \
--data-raw '{ "t": 5}' && \ 
curl -L -X POST 'http://localhost:7896/iot/json?k=service4&i=dev4' \
-H 'Content-Type: application/json' \
--data-raw '{ "t": 5}'
```

## Result

```json
curl -vX GET 'http://localhost:1026/v2/entities' \
-H 'fiware-service: service' \
-H 'fiware-servicepath: /' | python -mjson.tool


[
    {
        "TimeInstant": {
            "metadata": {},
            "type": "DateTime",
            "value": "2022-11-29T10:33:55.323Z"
        },
        "id": "Device-2:dev2",
        "status": {
            "metadata": {},
            "type": "Property",
            "value": null
        },
        "type": "Device-2"
    },
    {
        "TimeInstant": {
            "metadata": {},
            "type": "DateTime",
            "value": "2022-11-29T10:33:55.557Z"
        },
        "id": "Device-4:dev4",
        "status": {
            "metadata": {},
            "type": "Property",
            "value": null
        },
        "type": "Device-4"
    }
]
```

## Conclusions 

As we can see, all 2 measurements corresponding to the 2 groups that `autoprovision: true` were persisted. 
Thus, the flag seems working properly. 

Could you please reproduce the steps described here? Could you provide a similar report with curl requests and IoTA deployment / config?

**Comment by djs0109** [comment]
Yes of course!

## Deployment

```yml
  iot-agent:
    image: telefonicaiot/iotagent-json:latest
    hostname: iot-agent
    container_name: "iot-agent"
    restart: always
    depends_on:
      - mongo-db
    ports:
      - "4041:4041"
      - "7896:7896"
    networks:
      - fiware
    environment:
      - IOTA_CB_HOST=orion
      - IOTA_CB_PORT=1026
      - IOTA_NORTH_PORT=4041
      - IOTA_REGISTRY_TYPE=mongodb
      - IOTA_LOG_LEVEL=DEBUG
      - IOTA_CB_NGSI_VERSION=v2
      - IOTA_MONGO_HOST=mongo-db
      - IOTA_MONGO_PORT=27017
      - IOTA_MONGO_DB=iotagentjson
      - IOTA_PROVIDER_URL=http://iot-agent:4041
      - IOTA_DEFAULT_RESOURCE=/iot/json
      - IOTA_HTTP_PORT=7896
      - IOTA_MQTT_HOST=mosquitto
      - IOTA_MQTT_PORT=1883
      - IOTA_DEFAULT_TRANSPORT=MQTT
      - IOTA_MQTT_PROTOCOL=mqtt
      - IOTA_MQTT_KEEPALIVE=60
```

## Service Creation
same as above

## Data sent
The data is sent via MQTT
```
topic: /json/service1/dev1/attrs
payload: {"t":5}


topic: /json/service2/dev2/attrs
payload: {"t":5}


topic: /json/service3/dev3/attrs
payload: {"t":5}


topic: /json/service4/dev4/attrs
payload: {"t":5}
```

## Results
```yml
curl --location --request GET 'http://localhost:1026/v2/entities/' \
--header 'fiware-service: test' \
--header 'fiware-servicepath: /'

[
    {
        "id": "Device-2:dev2",
        "type": "Device-2",
        "TimeInstant": {
            "type": "DateTime",
            "value": "2022-12-01T09:13:51.754Z",
            "metadata": {}
        },
        "status": {
            "type": "Property",
            "value": null,
            "metadata": {}
        }
    },
    {
        "id": "Device-4:dev4",
        "type": "Device-4",
        "TimeInstant": {
            "type": "DateTime",
            "value": "2022-12-01T09:14:01.982Z",
            "metadata": {}
        },
        "status": {
            "type": "Property",
            "value": null,
            "metadata": {}
        }
    }
]
```

## Conclusions
We see that service 1, 3, 4 works as expected, but service 2 did not. In service 2, where `"explicitAttrs": false` and `"autoprovision": true`, the expected behavior is:
1. The entity should be created (✓)
2. The attribute "t" should also be created (x)

If we add `- IOTA_APPEND_MODE=true` to `env`, and then **only** send `dev2` data again, we can see that the attribute `t` is crceated. 

```yml
curl --location --request GET 'http://localhost:1026/v2/entities/' \
--header 'fiware-service: test' \
--header 'fiware-servicepath: /'

[
    {
        "id": "Device-2:dev2",
        "type": "Device-2",
        "TimeInstant": {
            "type": "DateTime",
            "value": "2022-12-01T09:30:28.812Z",
            "metadata": {}
        },
        "status": {
            "type": "Property",
            "value": null,
            "metadata": {}
        },
        "t": {
            "type": "string",
            "value": 5,
            "metadata": {
                "TimeInstant": {
                    "type": "DateTime",
                    "value": "2022-12-01T09:30:28.812Z"
                }
            }
        }
    },
    {
        "id": "Device-4:dev4",
        "type": "Device-4",
        "TimeInstant": {
            "type": "DateTime",
            "value": "2022-12-01T09:14:01.982Z",
            "metadata": {}
        },
        "status": {
            "type": "Property",
            "value": null,
            "metadata": {}
        }
    }
]
```

## Summary
`autoprovision` can not overwrite `appendMode/IOTA_APPEND_MODE`
