### ISSUE TITLE
Unable send commands from Orion to Device

### ISSUE THREAD

**Issue by jason-fox** [telefonicaid/iotagent-node-lib#1464]
### IoT Agent Node Lib version the issue has been seen with

3.2.0

### Bound or port used (API interaction)

Southbound (Devices data API), Northbound (Provision API and NGSI Interactions)

### NGSI version

NGSIv2

### Are you running a container?

Yes, I am using a container (Docker, Kubernetes...)

### Image type

normal

### Expected behaviour you didn't see

This is a result of #1421  -specifically the removal of the intial Entity.

When I create a Group

```json
 {
     "apikey":      "3020035",
     "cbroker":     "http://orion:1026",
     "entity_type": "Bell",
     "resource":    "/iot/d",
     "protocol":    "PDI-IoTA-UltraLight",
     "transport":   "HTTP",
 },
```

and provision an actuator:

```json
{
      "device_id": "bell001",
      "entity_name": "Bell:001",
      "entity_type": "Bell",
      "endpoint": "http://iot-sensors:1041/iot/bell001",
      "commands": [ 
        {
          "name": "ring",
          "type": "command"
        }
      ],
      "static_attributes": [
          {"name": "refStore", "type": "Relationship","value": "urn:ngsi-ld:Store:001"}
      ]
    },
```

No Entity is created in the context broker.

### Unexpected behaviour you saw

Sincent he initial insert of an Entity has been removed, so 

```console
curl -L 'http://localhost:1026/v2/entities/Bell:001?options=keyValues' \
-H 'fiware-service: openiot' \
-H 'fiware-servicepath: /'
```

is just returning:

```json
{
    "id": "Bell:001",
    "type": "Bell",
    "ring": ""
}
```

However, I cannot PUT or PATCH an Entity with Orion

```console
curl -L -X PUT 'http://localhost:1026/v2/entities/Bell:001/attrs/ring' \
-H 'fiware-service: openiot' \
-H 'fiware-servicepath: /' \
-H 'Content-Type: application/json' \
-d '{
      "type" : "command",
      "value" : ""
}'
```

is returning:

```json
{
    "error": "NotFound",
    "description": "The requested entity has not been found. Check type and id"
}
```

### Configs

```yaml
  orion:
    labels:
      org.fiware: 'tutorial'
    image: quay.io/fiware/orion:3.10.1
    hostname: orion
    container_name: fiware-orion
    depends_on:
      - mongo-db
    networks:
      - default
    expose:
      - 1026
    ports:
      - 1026:1206
    command: -dbhost mongo-db -logLevel DEBUG
    healthcheck:
      test: curl --fail -s http://orion:1026/version || exit 1
      interval: 5s

  # IoT-Agent is configured for the UltraLight Protocol
  iot-agent:
    labels:
      org.fiware: 'tutorial'
    image: quay.io/fiware/iotagent-ul:2.4.0-distroless
    hostname: iot-agent
    container_name: fiware-iot-agent
    depends_on:
      - mongo-db
    networks:
      - default
    ports:
      - "${IOTA_NORTH_PORT}:${IOTA_NORTH_PORT}" # localhost:4041
      - "${IOTA_SOUTH_PORT}:${IOTA_SOUTH_PORT}" # localhost:7896
    environment:
      - IOTA_CB_HOST=orion # name of the context broker to update context
      - IOTA_CB_PORT=${ORION_PORT} # port the context broker listens on to update context
      - IOTA_NORTH_PORT=${IOTA_NORTH_PORT}
      - IOTA_REGISTRY_TYPE=mongodb #Whether to hold IoT device info in memory or in a database
      - IOTA_LOG_LEVEL=INFO # The log level of the IoT Agent
      - IOTA_TIMESTAMP=true # Supply timestamp information with each measurement
      - IOTA_CB_NGSI_VERSION=v2 # use NGSIv2 when sending updates for active attributes
      - IOTA_AUTOCAST=true # Ensure Ultralight number values are read as numbers not strings
      - IOTA_MONGO_HOST=mongo-db # The host name of MongoDB
      - IOTA_MONGO_PORT=${MONGO_DB_PORT} # The port mongoDB is listening on
      - IOTA_MONGO_DB=iotagentul # The name of the database used in mongoDB
      - IOTA_HTTP_PORT=${IOTA_SOUTH_PORT} # The port used for device traffic over HTTP
      - IOTA_PROVIDER_URL=http://iot-agent:${IOTA_NORTH_PORT}
    healthcheck:
      interval: 5s
```
