### ISSUE TITLE
[Bug] Context availability registration for NGSIv1 uses isDomain property for attributes

### ISSUE THREAD

**Issue by dcalvoalonso** [telefonicaid/iotagent-node-lib#701]
Doing some e2e integration tests with LWM2M IoT Agent (https://github.com/telefonicaid/lightweightm2m-iotagent/pull/141), I have realized that there is a potential bug related to context availability registration for NGSIv1.

As you can see in multiple files used in the mocks of the unit tests (e.g., https://github.com/telefonicaid/iotagent-node-lib/blob/master/test/unit/examples/contextAvailabilityRequests/registerIoTAgent1.json), the library include `isDomain` property for the attributes. This is done in https://github.com/telefonicaid/iotagent-node-lib/blob/master/lib/services/devices/registrationUtils.js#166.

Nevertheless, when such a request is sent to the CB, the answer is:

```
{
    "registrationId": "000000000000000000000000",
    "errorCode": {
        "code": "400",
        "reasonPhrase": "Bad Request",
        "details": "JSON Parse Error: unknown field: /contextRegistrations/contextRegistration/attributes/attribute/isDomain"
    }
}
```

**Comment by dcalvoalonso** [comment]
@fgalan What do you think? Is this related to some recent change in NGSI and the CB?

**Comment by fgalan** [comment]
I think you are right. CB removes usage of isDomain recently (in particular in PR https://github.com/telefonicaid/fiware-orion/pull/3324). This field hasn't been never used in Orion.

I think the solution is pretty easy: just remove from .json used by the tests.

(As side-note: in which scenario are IOTAs using context availability subscriptions? Or it is just a feature implemented some place in the library but actually never used? In that case maybe we should apply the same treament you plan for XML in issue https://github.com/telefonicaid/iotagent-node-lib/issues/691  and eventually remove it).

**Comment by arilwan** [comment]
Hi, 

Is this the reason why Orion generate the following error, when I tried pre-provision a device:
```
{
    "message": "Request error connecting to the Context Broker: {\"code\":\"400\",\"reasonPhrase\":\"Bad Request\",\"details\":\"JSON Parse Error: unknown field: /contextRegistrations/contextRegistration/attributes/attribute/isDomain\"}",
    "name": "BAD_REQUEST"
}
```
This is the curl command I'm sending:
```
(curl localhost:4041/iot/devices -s -S --header 'Content-Type: application/json' \
  --header 'Accept: application/json' --header 'fiware-service: factory' --header 'fiware-servicepath: /robots' \
  -d @- | python -mjson.tool) <<EOF
{
  "devices": [
      {
        "device_id": "robot1",
        "entity_type": "Robot",
        "attributes": [
          {
            "name": "Battery",
            "type": "number"
          }
        ],
        "lazy": [
          {
            "name": "Message",
            "type": "string"
          }
        ],
        "commands": [
          {
            "name": "Position",
            "type": "location"
          }
        ],
      "internal_attributes": {
        "lwm2mResourceMapping": {
          "Battery" : {
            "objectType": 7392,
            "objectInstance": 0,
            "objectResource": 1
          },
          "Message" : {
            "objectType": 7392,
            "objectInstance": 0,
            "objectResource": 2
          },
          "Position" : {
            "objectType": 7392,
            "objectInstance": 0,
            "objectResource": 3
          }
        }
      }
    }
  ]
}
EOF
```

I'm using this `docker-compose` file:
```
version: "3.1"

services:
        mongo:
                image: mongo:3.6
                command: --nojournal
                ports: 
                 - "27017:27017"
                expose:
                 - "27017"
        orion:
                image: fiware/orion
                links:
                 - mongo
                ports: 
                 - "1026:1026"
                command: -dbhost mongo -logLevel DEBUG
                depends_on:
                 - mongo
                expose: 
                 - "1026"
        lightweightm2m-iotagent:
                image: telefonicaiot/lightweightm2m-iotagent
                hostname: idas
                links:
                 - orion
                expose: 
                 - "4041"
                 - "5684"
                ports: 
                 - "4041:4041"
                 - "5684:5684/udp"
        mosquitto:
                image: ansi/mosquitto
                ports: 
                 - "1883:1883"
                expose: 
                 - "1883"
``` 
Not sure how to fix this.
